name: CI / Coverage

on:
  workflow_dispatch:

  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

env:
  NX_CACHE: nx-cache

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install deps
        uses: ./.github/workflows/composite/npm

      - name: Cache Nx
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/nx
          key: ${{ env.NX_CACHE }}-${{ hashFiles('**/package-lock.json') }}-${{ matrix.target }}-${{ matrix.index }}-${{ github.sha }}
          restore-keys: |
            ${{ env.NX_CACHE }}-${{ hashFiles('**/package-lock.json') }}-${{ matrix.target }}-${{ matrix.index }}-
            ${{ env.NX_CACHE }}-${{ hashFiles('**/package-lock.json') }}-
            ${{ env.NX_CACHE }}-

      - name: npm run test:coverage:all
        run: npm run test:coverage:all

      - uses: qltysh/qlty-action/coverage@v1
        if: ${{ hashFiles('coverage/**/lcov.info') }}
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/**/lcov.info